import {
  SPY_FAIRNESS_STORAGE_KEY,
  SPY_SESSION_STORAGE_KEY,
  SPY_STORAGE_NAMESPACE,
  SPY_STORAGE_SCHEMA_VERSION,
} from "../../identity";

export const STORAGE_SCHEMA_VERSION = SPY_STORAGE_SCHEMA_VERSION;

export const GAME_SESSION_STORAGE_KEY = SPY_SESSION_STORAGE_KEY;

export const FAIRNESS_HISTORY_STORAGE_KEY = SPY_FAIRNESS_STORAGE_KEY;

export const LEGACY_GAME_SESSION_KEYS = [
  `${SPY_STORAGE_NAMESPACE}:session`,
] as const;

export const LEGACY_FAIRNESS_HISTORY_KEYS = [
  `${SPY_STORAGE_NAMESPACE}:fairness`,
] as const;
